#!/bin/bash
set -e

# setup git prompt
#curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh >"$XDG_CONFIG_HOME"/bash/git-prompt.sh

# Delete existing symbolic links on windows
# ln -sf command yields a copy in git-bash
if [[ "$OSTYPE" == "msys"* ]]; then
	rm -f "$HOME/.bashrc"
	rm -f "$HOME/.dircolors"
	rm -f "$HOME/.inputrc"
	rm -f "$HOME/.profile"
	rm -f "$HOME/.bash_profile"
	rm -rf "$HOME/scripts"
fi

# Symbolic link/copy essential bash files to home directory
ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"
ln -snf "$PWD/scripts" "$HOME/scripts"

# Create the XDG directory structure
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CACHE_HOME"
mkdir -p "$XDG_DATA_HOME"
mkdir -p "$XDG_STATE_HOME"
mkdir -p "$XDG_BIN_HOME"

for i in vim gh git tmux lynx pomo alacritty; do
  cd $i && ./setup
  cd -
done
