#!/bin/sh

if [ -z "$(which vim)" -o -z "$(which vimtutor)" ]; then
  echo "Warning, doesn't look like you have full Vim version."
fi

if [[ "$OSTYPE" == "msys"* ]]; then
	rm -f "$HOME/.vimrc"
	rm -f "$HOME/.vim/autoload/plug.vim"
fi

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/.vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"
