#!/bin/bash
set -e

apt update
apt install build-essential \
	libssl-dev \
	zlib1g-dev \
	libbz2-dev \
	libreadline-dev \
	libsqlite3-dev curl \
	libncursesw5-dev \
	xz-utils \
	tk-dev \
	libxml2-dev \
	libxmlsec1-dev \
	libffi-dev \
	liblzma-dev \
	make \
	cmake \
	pkg-config \
	libfreetype6-dev \
	libfontconfig1-dev \
	libxcb-xfixes0-dev \
	libxkbcommon-dev \
	python3 \
	nmap \
	jq \
	lynx \
	uidmap \
	entr \
	tmux \
	gh \
	duck \
	gpt \
	autoconf \
	ncurses-base \
	libncurses5-dev \
	remmina \
	alacritty \
	vim \
	mc \
	universal-ctags
