#!/data/data/com.termux/files/usr/bin/bash
#set -euo pipefail

. "$HOME/.bashrc"

result="$(termux-clipboard-get 2>/dev/null)"
if [[ ! -z $result ]]; then
  bash mind log "$result"
  termux-toast "Logged to Captain’s Log"
fi
