#!/usr/bin/env bash

_have() { type "$1" &>/dev/null; }

declare OPENAI_API_KEY
OPENAI_API_KEY="$(head -1 "$XDG_CONFIG_HOME/gpt/token")"
export OPENAI_API_KEY

! _have mods && echo "requires charmbracelet/mods" && exit 1

mods --no-limit --status-text "Ummm" "$*" | glow
